#source 'git@192.168.12.16:Source/IOS/Pod-Specs.git'
#source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '11.0'

target 'JKOLogger_Example' do
  pod 'JKOLogger', :path => '../'

  target 'JKOLogger_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
